version: "3.8"
services:
  mongo:
    image: mongo
    container_name: startup-db
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
  app:
    environment:
      - MONGODB_URL=mongodb://mongo
      - MONGODB_PORT=27017
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=root
    ports:
      - 8080:8080
    build:
      context: .
    container_name: startup-app
    restart: always
    depends_on:
      - mongo