version: "3.8"
services:
  mongo:
    image: mongo:4
    container_name: mongo
    ports:
      - 27017:27017
    healthcheck:
      test: mongo
      interval: 1s
      retries: 10
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root